title: NuriFlex Docs Home
title_separator: "-"
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
# remote_theme: carlosperate/jekyll-theme-rtd

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings:
site_author: NuriFlex Co., Ltd. Product Management team
repo_url: "https://github.com/nuridocs/nuridocs.github.io"
edit_on_github: true
github_docs_folder: False
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist

# plugins:
#  - jekyll-remote-theme

url: https://nuridocs.github.io
# baseurl: /p1 # the subpath of the site, represents version in this example repo

logo: 'https://cdn.gukjenews.com/news/photo/202105/2231928_2223755_5416.jpeg'

theme: jekyll-theme-rtd

permalink: /:categories/:title

###
production_url: https://nuridocs.github.io
locale: en_US
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true

plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-toc #210910

jekyll-mentions:
  base_url: https://github.com